GET http://localhost:8000/mypost HTTP/1.1

# POST http://localhost:5000/createpost HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1Zjc3NGQ0OWZiYTU1NjJlZDBjMDYxMWYiLCJpYXQiOjE2MDE2NTQ1Mzh9.gMjJMzyQLQTavvauMa2CMJ6gAmqIMDckkSHMCwTE1Bw
# Content-Type: : application/json

# {
#     "title":"amazing",
#     "body":"new body"
# }